### ISSUE TITLE
[ISSUE] Website is not up-to-date

### ISSUE THREAD

**Issue by GaetanVandenBergh** [MrSweeter/joorney#35]
Installation steps is not up-to-date with rollup. 
Chrome link image should be the main part now it's published

https://mrsweeter.github.io/joorney/index.html#installation

**Comment by ande-odoo** [comment]
Feature idea:
In the center of the landing page, a list of the features (at the place of the current grid)
You could switch the list from grid view (similar to mobile) to list view 
The grid view is only the feature icons + tooltip
The list view has a few columns: Icon, feature name, short desc, etc

**Comment by GaetanVandenBergh** [comment]
![image](https://github.com/user-attachments/assets/0f78d75d-6787-4692-a017-0342c718c542)
![image](https://github.com/user-attachments/assets/df5e01a7-a05a-41ca-b00c-06f9d5b4c58f)
![image](https://github.com/user-attachments/assets/7f613c19-6c65-44ed-a403-80cd06a3962e)
