### ISSUE TITLE
Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.

### ISSUE THREAD

**Issue by GaetanVandenBergh** [MrSweeter/joorney#45]
**To Reproduce**
1. In Odoo, open window action with xml_id `action_general_configuration`
2. Change name to "Cài đặt" (not Latin1 character)
3. Back to home
4. Open Settings app

**Actual result**
Cache system will fail to save due to
```javascript
Uncaught (in promise) InvalidCharacterError: 
Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

**Expected behavior**
No issue, cache system will save the request result

**Stackoverflow thread**
https://stackoverflow.com/questions/23223718/failed-to-execute-btoa-on-window-the-string-to-be-encoded-contains-characte

**Comment by MrSweeter** [comment]
![image](https://github.com/user-attachments/assets/93325b57-a450-457a-82db-11bca5696b6e)

Need to try-catch the read/save to avoid conflict with previous version or future version
