### ISSUE TITLE
[17.0] metadata tooltip shows itself on top of the debug menu drop down 

### ISSUE THREAD

**Issue by mao-odoo** [MrSweeter/joorney#58]
**Describe the bug**
The metadata tool tip drop down is shown on top of the debug menu tooltip, rendering the first half of the debug menu unusable.

**To Reproduce**
1. Go to an odoo database in v17
2. Activate the metadata tool tip setting of joorney for that website
3. activate debug mode
4. click on the debug menu
5. hover over the drop down menu (the one from odoo)

**Expected behaviour**
The Joorney tooltip should not obscure the drop down menu

**Environment**
Browser information : Version 129.0.6668.103 (Official Build) (x86_64)  (macos)
Extension version: Joorney 2.3.0.16 (2.3.0.24270)

**Screenshots**
![Screenshot 2024-10-23 at 16 52 23](https://github.com/user-attachments/assets/ee7250e7-c12b-45c5-b65e-38d3857f19b1)

**Additional context**
N/A

**Comment by MrSweeter** [comment]
https://github.com/MrSweeter/joorney/issues/54
Should be deployed soon

**Comment by MrSweeter** [comment]
Should be fixed in #56
Due to #54
